### ISSUE TITLE
I'm login for "login-as" function

### ISSUE THREAD

**Issue by Lexys-zz** [solitweb/laravel-directadmin#10]
If I have logged to Direct Admin as Reseller using API, is it possible to login as user and make API call's under user level?

**Comment by joshuadegier** [comment]
["Login-as" with the API:](https://www.directadmin.com/api.php)

Note that you can use the "login-as" feature with the API if you want to make User Level API calls for your clients, but don't know their passwords. The way you do that is setup your API to make the User Level API call normally, but instead of using $username = "clientuser"; (since you don't know their password) you'd instead use: $username = "admin|clientuser"; and specify the admin password. This can be used for any Admin or Reseller who controls the client they're logging into. Note that an Admin can control everyone, so they can login to anyone's account with this method. A Reseller can obviously only log into their own client's accounts. You can also test this feature out at the standard DA login page.. enter the "admin|user" username instead of "admin", along with the admin password, and you'll be logged in as "user" with your browser.
