### ISSUE TITLE
installation command wil not work

### ISSUE THREAD

**Issue by superboys2017** [solitweb/laravel-directadmin#16]
the instal command is broken

**Comment by stijnvanouplines** [comment]
Can you try again? I updated composer.json file.

**Comment by thedejavunl** [comment]
Hi Stijn,
Sorry that I reply to this old thread, I see that you fixed the composer.json versions for Laravel 7.X.
But Packagist didn't take over your package, it is still showing the version from 2019.
Users with Laravel 7.X can't use the package now because of this issue.

EDIT: I see that it is in the dev-master version only! 👍

**Comment by stijnvanouplines** [comment]
I tagged a new version (1.0.7)

**Comment by thedejavunl** [comment]
Thank you very much for your quick reply and solution! 👍

**Comment by stijnvanouplines** [comment]
No problem! 😉
